pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: my-pipeline-pod
spec:
  containers:
  - name: dockerindocker
    image: summerwind/actions-runner-dind:v2.313.0-ubuntu-20.04
    tty: true
"""
        }
    }
    stages {
        stage("Deploy") {
            steps {
                container("dockerindocker"){
                sh "docker build -t panda:v1 ."  // Run shell command to list files
                echo "Hello, Jenkins!"  // Print a message
                }

            }
        }
    }
}
