pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: my-pipeline-pod
spec:
  containers:
  - name: dockerindocker
    image: docker:dind
    tty: true
    securityContext:
      privileged: true  # Required for Docker-in-Docker
"""
        }
    }
    stages {
        stage("Deploy") {
            steps {
                container("dockerindocker") {
                    sh """
                    # Start the Docker daemon
                    dockerd &
                    sleep 5  # Wait for Docker to start
                    
                    # Verify Docker is running
                    docker info
                    
                    # Build the Docker image
                    docker build -t panda:v1 .
                    """
                    echo "Hello, Jenkins!"
                }
            }
        }
    }
}
