pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: my-pipeline-pod
spec:
  containers:
  - name: dockerindocker
    image: docker:dind
    tty: true
    securityContext:
      privileged: true  # Required for Docker-in-Docker
"""
        }
    }
    stages {
        stage("Deploy") {
            steps {
                container("dockerindocker") {
                    sh """

                    dockerd &
                    sleep 5 
                    docker info
                    docker build -t 058264520519.dkr.ecr.us-east-1.amazonaws.com/panda:v1 .
                    docker push 058264520519.dkr.ecr.us-east-1.amazonaws.com/panda:v1
                    """
                    echo "Hello, Jenkins!"
                }
            }
        }
    }
}
